from django.contrib.gis.db import models

class Transaction(models.Model):
  pin               = models.CharField('Property ID number', max_length=14, db_index=True)
  amount_prime      = models.FloatField('Mortgage amount', null=True) 
  doc		    = models.CharField('Document ID', null=True, max_length=100)
  date_doc          = models.DateTimeField('Date documented', null=True)
  date_rec          = models.DateTimeField('Date recorded', null=True)
  buyer	    	    = models.CharField('Buyer', max_length=100, null=True)
  buyer_type	    = models.CharField('Buyer type', max_length=10, null=True)
  seller	    = models.CharField('Seller', max_length=100, null=True)
  seller_type	    = models.CharField('Seller type', max_length=10, null=True)
  non_condo	    = models.IntegerField('Not a condo?', null=True) 
  purchase_less_20k = models.IntegerField('Low-value transaction?', null=True) 
  business_buyer    = models.IntegerField('Buyer is a business?', null=True) 
  yq_doc            = models.IntegerField('Year and quarter recorded', null=True)
  yeard             = models.IntegerField('Year recorded', null=True)
  apt               = models.CharField('Apartment numer', max_length=10, null=True)
  direction         = models.CharField('Street direction', max_length=2, null=True)
  houseno           = models.CharField('House number', max_length=10, null=True)
  street            = models.CharField('Street name', max_length=50, null=True)
  suffix            = models.CharField('Street suffix', max_length=10, null=True)
  addr_final        = models.CharField('First line of address', max_length=100, null=True)
  city_final        = models.CharField('City name', max_length=100, null=True)
  lat_y             = models.FloatField('Latitude', null=True)
  long_x            = models.FloatField('Longitude', null=True)
  tract_fix         = models.FloatField('2000 census tract', null=True)
  no_tract_info     = models.NullBooleanField('No geography information', null=True)
  ca_num            = models.IntegerField('Community area number', null=True)
  ca_name           = models.CharField('Community area', max_length=100, null=True)
  place             = models.CharField('Cook County subdivison', max_length=100, null=True)
  gisdate           = models.CharField('GIS file reference date', max_length=100, null=True)
  ptype	            = models.ForeignKey('PropertyTypes')
  residential       = models.IntegerField('Residential?', null=True)
  adj_yq            = models.IntegerField('Adjusted quarter', null=True)
  adj_yd            = models.IntegerField('Adjusted day', null=True)
  loc               = models.PointField(null=True,srid=3435)
  objects           = models.GeoManager()
  def __unicode__(self):
    return unicode(self.pin)
  class Meta:
    app_label = 'landbank_data'
